### ISSUE TITLE
Behind Traefik : Too many redirect

### ISSUE THREAD

**Issue by jurnet** [AdnanHodzic/ansible-role-containerized-wordpress#2]
Hello,
I'm trying to do my best but it doesn't work : **Too many redirect**
I'm behind traefik and that is the docker-compose template generated : 
Do you see something wrong?

```
version: '2.1'

services:
  https-portal:
    image: steveltn/https-portal:1
    container_name: https
    volumes:
      - ./logs/nginx:/var/log/nginx
    ports:
      - '801:80'
      - '802:443'
    environment:
      CLIENT_MAX_BODY_SIZE: '100M'
      GZIP: 'on'
      DOMAINS: 'lf.jpj.ovh -> http://wordpress:80'
      STAGE: 'local'
    restart: unless-stopped
    networks:
      - web
      - lf
    labels:
      traefik.enable: "true"
      traefik.http.routers.lf.rule: "Host(`lf.jpj.ovh`)"
      traefik.http.routers.lf.entrypoints: "websecure"

  wordpress:
    depends_on:
      db:
        condition: service_healthy
    image: wordpress:5.4.2-apache
    container_name: wp
    volumes:
      - ./wordpress:/var/www/html
      - ./wordpress/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    environment:
      WORDPRESS_DB_USER: 'admin'
      WORDPRESS_DB_NAME: 'lf'
      WORDPRESS_DB_PASSWORD: 'admin'
      WORDPRESS_DB_HOST: 'db'
      MYSQL_PORT_3306_TCP: '3306'
    restart: unless-stopped
    networks:
      - lf
   
  db:
    image: mysql:5.7
    container_name: db
    volumes:
      - ./wp-db-data:/var/lib/mysql
    healthcheck:
      test: "/usr/bin/mysql --user=root --password='admin' --execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 20s
      retries: 10
    environment:
      MYSQL_ROOT_PASSWORD: 'admin'
      MYSQL_DATABASE: 'lf'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin'
    restart: unless-stopped
    networks:
      - lf

networks:
  web:
    external:
      name: web
  lf:  

```

I have a wildcard on jpj.ovh
And I want to test Wordpress as subdomain like lf.jpj.ovh
I don't know If I have to use the same networks.
Any idea ?
